### ISSUE TITLE
Creating autoMMM library based on your code.

### ISSUE THREAD

**Issue by ghost** [sibylhe/mmm_stan#23]
Hello, I've had the idea to create a media mix modeling library in python for a while. I really liked your model, so I wrapped it in a class that would make it easy to use. You can see the start of it here.

https://github.com/NichoGustafson/autoMMM

So far I haven't tested the code much, but I plan to work on it much more in the coming week. I'd like to add, in addition to your Bayesian model, an interface for simpler models as well. If you would like to collaborate on this project, please let me know; I'm very busy with work, so I need all the help I can get.

Thanks! 

Nick

**Comment by sibylhe** [comment]
Hi Nick,

I'm thrilled to know you're creating a library based on this! 

I'm not sure about the generability of my code. It was created for this dataset, and will yield only a baseline model. In practice, MMM is very versatile, a couple of things need to be customized and tuned to fit a specific case.

1. Variables. This model: sales ~ impressions, while someone prefers sales ~ spend (combine model2 and model3), someone has monthly data, etc.
2. Priors. I used relatively strong priors for coefficients because I normalized the variables. If a user chooses not to normalize the variables, he may need to switch to weaker priors. 
3. Additive or multiplicative model structure. 
4. Adstock parameters need tuning. See #15 for details.

How far do you want to go, what's your plan? And let me know how I can help. I could work on it on weekends and in free time.

Sibyl

**Comment by sibylhe** [comment]
Feel free to reopen if you have any updates.
